chore: nas

diff --git a/src/code/project/Dockerfile b/src/code/project/Dockerfile
--- a/src/code/project/Dockerfile
+++ b/src/code/project/Dockerfile
@@ -5,4 +5,15 @@ FROM nginx
 COPY index.html /mnt/index.html
 
 # 映射文件
-RUN ln -sf /mnt/index.html /usr/share/nginx/html/index.html
+ENV PERSISTENCE_NAS /mnt/auto
+RUN set -eux; \
+	if [ ! -d  $PERSISTENCE_NAS ]; then \
+		echo "$PERSISTENCE_NAS Not found"; \
+		echo "create $PERSISTENCE_NAS"; \
+	else \
+		echo -e "directory already exists"; \
+	fi; \
+	\
+	rm -rf /usr/share/nginx/html; \
+	ln -sf /mnt /usr/share/nginx/html
+# END
